apiVersion: v1
kind: Service
metadata:
  name: cloud-console-service
  namespace: management
spec:
  type: NodePort
  selector:
    app: cloud-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      